default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: felipe
  password: "123456"
  host: localhost

development:
  <<: *default
  database: api_nfae_development

test:
  <<: *default
  database: api_nfae_test

production:
  <<: *default
  database: <%= ENV["DB_NAME"] %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
  port: 5432

